name: Generate Cache
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  build:
    strategy:
      matrix:
        package:
          - "nixpkgs#php81Extensions.grpc"
          - "nixpkgs#php81Extensions.redis"
          - "nixpkgs#php82Extensions.grpc"
          - "nixpkgs#php82Extensions.redis"
          - "github:fossar/nix-phps#php80"
          - "github:fossar/nix-phps#php74"
        arch:
          - "x86_64-darwin"
          - "aarch64-darwin"
        
    runs-on: self-hosted
    steps:
      - name: Build
        run: cachix push shopware $(nix build ${{ matrix.package }} --system ${{ matrix.arch }} --no-link --print-out-paths)

