name: Generate Cache
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  build:
    strategy:
      matrix:
        os:
          - "macos-latest" # mac x64
          - "ARM64" # mac arm64 (m1)
        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@master
        if: ${{ matrix.os }} == "macos-latest"
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Use Shopware Cache
        uses: cachix/cachix-action@master
        if: ${{ matrix.os }} == "macos-latest"
        with:
          name: shopware
          skipPush: true
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Redis (8.1)
        run: cachix push shopware $(nix build nixpkgs#php81Extensions.redis --no-link --print-out-paths)
        
      - name: Build GRPC (8.1)
        run: cachix push shopware $(nix build nixpkgs#php81Extensions.grpc --no-link --print-out-paths)
        
      - name: Build Redis (8.2)
        run: cachix push shopware $(nix build nixpkgs#php82Extensions.redis --no-link --print-out-paths)
        
      - name: Build GRPC (8.2)
        run: cachix push shopware $(nix build nixpkgs#php82Extensions.grpc --no-link --print-out-paths)

